namespace:
  name: prod
 
service:
  port: 4111
  type: ClusterIP

image:
  repository: uttaranikki/techtrends 
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 3

resources:
  requests:
    cpu: 70m
    memory: 256Mi

configmap:
  data: "version: 1.17.0"
