namespace:
  name: staging 
 
service:
  port: 8111
  type: ClusterIP

image:
  repository: nd064_course_1 
  tag: 1.18.0
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  requests:
    cpu: 50m
    memory: 128Mi

configmap:
  data: "version: 1.18.0"
