namespace:
  name: staging
 
service:
  port: 4111
  type: ClusterIP

image:
  repository: uttaranikki/techtrends 
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 5
resources:
  requests:
    cpu: 50m
    memory: 128Mi

configmap:
  data: "version: 1.18.0"
