namespace:
  name: staging 
 
service:
  port: 5111
  type: ClusterIP

replicaCount: 3

resources:
  requests:
    cpu: 300m
    memory: 90Mi
  limits:
    memory: "128Mi"
    cpu: "500m"    
